Traceback (most recent call last):
  File "/home/runner/work/pymedphys/pymedphys/.venv/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/runner/work/pymedphys/pymedphys/.venv/lib/python3.8/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/runner/work/pymedphys/pymedphys/.venv/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/runner/work/pymedphys/pymedphys/.venv/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.8.7/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/runner/work/pymedphys/pymedphys/.venv/lib/python3.8/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/home/runner/work/pymedphys/pymedphys/.venv/lib/python3.8/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/runner/work/pymedphys/pymedphys/.venv/lib/python3.8/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
gamma_options = {
    'dose_percent_threshold': 1,
    'distance_mm_threshold': 1,
    'lower_percent_dose_cutoff': 20,
    'interp_fraction': 10,  # Should be 10 or more for more accurate results
    'max_gamma': 2,
    'random_subset': None,
    'local_gamma': True,
    'ram_available': 2**29  # 1/2 GB
}
    
gamma = pymedphys.gamma(
    axes_reference, dose_reference, 
    axes_evaluation, dose_evaluation, 
    **gamma_options)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mValueError[0m                                Traceback (most recent call last)
[0;32m<ipython-input-11-a68b2651393b>[0m in [0;36m<module>[0;34m[0m
[1;32m     10[0m }
[1;32m     11[0m [0;34m[0m[0m
[0;32m---> 12[0;31m gamma = pymedphys.gamma(
[0m[1;32m     13[0m     [0maxes_reference[0m[0;34m,[0m [0mdose_reference[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m     14[0m     [0maxes_evaluation[0m[0;34m,[0m [0mdose_evaluation[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/work/pymedphys/pymedphys/lib/pymedphys/_gamma/implementation/shell.py[0m in [0;36mgamma_shell[0;34m(axes_reference, dose_reference, axes_evaluation, dose_evaluation, dose_percent_threshold, distance_mm_threshold, lower_percent_dose_cutoff, interp_fraction, max_gamma, local_gamma, global_normalisation, skip_once_passed, random_subset, ram_available, quiet)[0m
[1;32m    111[0m         [0mmax_gamma[0m [0;34m=[0m [0mnp[0m[0;34m.[0m[0minf[0m[0;34m[0m[0;34m[0m[0m
[1;32m    112[0m [0;34m[0m[0m
[0;32m--> 113[0;31m     options = GammaInternalFixedOptions.from_user_inputs(
[0m[1;32m    114[0m         [0maxes_reference[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m    115[0m         [0mdose_reference[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/work/pymedphys/pymedphys/lib/pymedphys/_gamma/implementation/shell.py[0m in [0;36mfrom_user_inputs[0;34m(cls, axes_reference, dose_reference, axes_evaluation, dose_evaluation, dose_percent_threshold, distance_mm_threshold, lower_percent_dose_cutoff, interp_fraction, max_gamma, local_gamma, global_normalisation, skip_once_passed, random_subset, ram_available, quiet)[0m
[1;32m    243[0m             [0mmax_gamma[0m [0;34m=[0m [0mnp[0m[0;34m.[0m[0minf[0m[0;34m[0m[0;34m[0m[0m
[1;32m    244[0m [0;34m[0m[0m
[0;32m--> 245[0;31m         axes_reference, axes_evaluation = run_input_checks(
[0m[1;32m    246[0m             [0maxes_reference[0m[0;34m,[0m [0mdose_reference[0m[0;34m,[0m [0maxes_evaluation[0m[0;34m,[0m [0mdose_evaluation[0m[0;34m[0m[0;34m[0m[0m
[1;32m    247[0m         )

[0;32m~/work/pymedphys/pymedphys/lib/pymedphys/_gamma/utilities/core.py[0m in [0;36mrun_input_checks[0;34m(axes_reference, dose_reference, axes_evaluation, dose_evaluation)[0m
[1;32m     70[0m     [0mreference_coords_shape[0m [0;34m=[0m [0;34m([0m[0mlen[0m[0;34m([0m[0mitem[0m[0;34m)[0m [0;32mfor[0m [0mitem[0m [0;32min[0m [0maxes_reference[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m     71[0m     [0;32mif[0m [0mreference_coords_shape[0m [0;34m!=[0m [0mnp[0m[0;34m.[0m[0mshape[0m[0;34m([0m[0mdose_reference[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 72[0;31m         raise ValueError(
[0m[1;32m     73[0m             [0;34m"Length of items in axes_reference ({}) does not match the "[0m[0;34m[0m[0;34m[0m[0m
[1;32m     74[0m             "shape of dose_reference ({})".format(

[0;31mValueError[0m: Length of items in axes_reference (<generator object run_input_checks.<locals>.<genexpr> at 0x7f8eded05970>) does not match the shape of dose_reference ((152, 158, 254))
ValueError: Length of items in axes_reference (<generator object run_input_checks.<locals>.<genexpr> at 0x7f8eded05970>) does not match the shape of dose_reference ((152, 158, 254))

